import {addTopic_IDB} from "./indexeddb";
import {getTopic_IDB} from "./indexeddb";
import {getTopics_IDB} from "./indexeddb"
import {updateTopic_IDB} from "./indexeddb"
import {deleteTopic_IDB} from "./indexeddb"

import Topic from "./topics";

export default class Section {
    constructor(id, order, title, color, coordinateX, coordinateY, height, width, topics) {
        this.id = id; //id is generated by server?
        this.order = order;
        this.title = title;
        this.color = color;
        this.coordinateX = coordinateX;
        this.coordinateY = coordinateY;
        this.height = height;
        this.width = width;
        this.topics = topics;
    }

    addTopic(idText,sectionOrder,idTopic,topicOrder, title, color, coordX, coordY, height, width, call) {
        addTopic_IDB(idText,sectionOrder,idTopic,title,topicOrder,color,coordX,coordY,height,width, function (res) {
            call(res);
        })
    };

    getTopics(idText, sectionOrder,  call) {
       getTopics_IDB(idText,sectionOrder,function (res) {
           call(res);
       })
    };

    getTopic(idText, sectionOrder, topicOrder, call){
        getTopic_IDB(idText,sectionOrder,topicOrder, function (res) {
            call(res);
        })
    }

    updateTopic(idText,sectionOrder, topicOrder, topic, call) {
        updateTopic_IDB(idText,sectionOrder,topicOrder,topic, function (res) {
            call(res);
        })
    };

    deleteTopic(idText, sectionOrder, topicOrder) {
        deleteTopic_IDB(idText,sectionOrder,topicOrder)
    }
}


