const DB_NAME = "Textos";
const DB_VERSION = 1; // Use a long long for this value (don't use a float)
const DB_STORE_NAME = "My_Texts";

var db;

export default class Topic {
    constructor(id, order, title,color,coordinateX,coordinateY,height,width) {
        this.id = id; //id is generated by server?
        this.order = order;
        this.paragraph= "";
        this.title = title;
        this.color = color;
        this.coordinateX = coordinateX;
        this.coordinateY = coordinateY;
        this.height = height;
        this.width = width;
    }
}


